#!/usr/bin/env python3

import math
import sys

Q = 1024

def value_for_percent(p: int) -> int:
    if p == 0:
        # Unused in normal operation because input is clamped to >= 1%.
        # Keep a finite value to avoid -inf in the table.
        x = math.log(0.0001)
    else:
        x = math.log(p / 100.0)

    return int(round(x * Q))

def main() -> int:
    if len(sys.argv) != 2:
        print("usage: gen_dewpoint_lut.py <output_header>", file=sys.stderr)
        return 2

    out_path = sys.argv[1]

    values = [value_for_percent(p) for p in range(101)]

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Auto-generated by tools/gen_dewpoint_lut.py\n")
        f.write("// Do not edit manually.\n\n")
        f.write("#ifndef DEWPOINT_LUT_H\n")
        f.write("#define DEWPOINT_LUT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const int32_t dewpoint_ln_rh_q10[101] = {\n")

        for i in range(0, 101, 10):
            row = values[i:i + 10]
            f.write("    " + ", ".join(f"{v:6d}" for v in row) + ",\n")

        f.write("};\n\n")
        f.write("#endif // DEWPOINT_LUT_H\n")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())